---
kind: pipeline
name: test-pr
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate
  image: grafana/build-container:1.2.27
  name: generate
- commands:
  - make test
  depends_on:
  - generate
  image: grafana/build-container:1.2.27
  name: test
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: test-master
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make generate
  image: grafana/build-container:1.2.27
  name: generate
- commands:
  - make test
  depends_on:
  - generate
  image: grafana/build-container:1.2.27
  name: test
trigger:
  branch: master
  event:
  - push
type: docker
---
kind: signature
hmac: c7f3f21d16ec45a1faacbc3aa92198a399bd67966aee0acc6f4efde868bbdc19

...
